In [27]:
import keras.models
import tensorflow as tf
import numpy as np
import pandas as pd
import csv
from src.functions import initializers as ci # i.e., custom initializers
from src.functions.layers import ActivLin1D
from src.functions import activation_parameters as ap
from src.utils import data_handler as dh

# Get model weights and biases

## Load model

In [28]:
# Model save path:
inv_save_path = '/Users/francescomaraschin/Desktop/IntelligentVehicles/Project_NN_Conda/data/trained_models/inverse_model/inverse_model.h5'

inverse_model = tf.keras.models.load_model(filepath=inv_save_path,
                                            custom_objects={
                                                'MyInitializer': ci.MyInitializer,
                                                'ActivLin1D': ActivLin1D
                                            })

## Get training channel array

In [29]:
# dataset saved path:
direct_dataset_path = '/Users/francescomaraschin/Desktop/IntelligentVehicles/Project_NN_Conda/data/csv/forward_profiles.csv'
direct_dataset = dh.load_csv(direct_dataset_path)
channel_parameters = ap.activation_function_parameters(dataset=direct_dataset)

chan_array = channel_parameters[1][0]

## Get weights of model layers:

In [30]:
# initialise weights:
weights = [0.]*np.size(inverse_model.layers)
i = 0
for layer in inverse_model.layers:
    weights[i] = layer.get_weights()
    i = i +1

# Weights is a list of a list of arrays containing the weights and biases of each layer and NN
#weights

In [31]:
weights

[[],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [array([[-0.3013694 ],
         [-0.21401055],
         [-0.16725454],
         [-0.04437852],
         [ 0.0029236 ],
         [ 0.00625809],
         [-0.03809135],
         [ 0.04702611],
         [ 0.08145902],
         [ 0.20249932]], dtype=float32),
  array([0.00514109], dtype=float32)],
 [array([[-0.1438509 ],
         [-0.13459662],
         [-0.04960714],
         [-0.10883838],
         [ 0.0180884 ],
         [-0.02525126],
         [-0.08118733],
         [ 0.03148369],
         [ 0.06431846],
         [ 0.14356282]], dtype=float32),
  array([0.00514109], dtype=float32)],
 [array([[-0.12340202],
         [ 0.01467817],
         [-0.00300071],
         [ 0.00929729],
         [-0.07514442],
         [-0.10522723],
         [ 0.02867376],
         [ 0.00520092],
         [ 0.04415568],
         [-0.03207032]], dtype=float32),
  array([0.00514109], dtype=float32)],
 [array([[-0.00980137],
         [-0.03072

## Velocity layer weight of complete model:

In [24]:
# Isolate velocity weight:
vel_weight = weights[35]
# Convert to np array:
vel_weight = np.array(vel_weight)
# Remove dtype extension:
vel_weight = vel_weight.tolist()
# Reshape:
vel_weight = np.reshape(vel_weight , (1))

# Remember that there is only one weight without a bias in the whole model for the velocity
#vel_weight

## Pedal layer weights & biases

In [25]:
# Isolate pedal weights and biases
pedal_layer = weights[14:24]

# Separate pedal weights and biases:
pedal_weights = []
pedal_bias = []
for layer in pedal_layer:
    pedal_weights.append(layer[0])
    pedal_bias.append(layer[1])

# Convert to np array
pedal_weights_array = np.array(pedal_weights)
pedal_bias_array = np.array(pedal_bias)
# Remove dtype extension
pedal_weights_array = pedal_weights_array.tolist()
pedal_bias_array = pedal_bias_array.tolist()
# Reshape to make matrix ----> Columns = Weights
#                              Rows    = Different neural networks
pedal_weights_array = np.reshape(pedal_weights_array , (10,10))
pedal_bias_array = np.reshape(pedal_bias_array , (10,1))

#pedal_weights_array

## Save to csv

In [26]:
# Pedal Weights:
pd.DataFrame(pedal_weights_array).to_csv("data/csv/weightsBias&ChanArray/pedal_weights.csv", header=None, index=None)

# Pedal Bias:
pd.DataFrame(pedal_bias_array).to_csv("data/csv/weightsBias&ChanArray/pedal_biases.csv", header=None, index=None)

# Velocity Weight:
pd.DataFrame(vel_weight).to_csv("data/csv/weightsBias&ChanArray/velocity_weight.csv", header=None, index=None)

# Channel Array:
pd.DataFrame(chan_array).to_csv("data/csv/weightsBias&ChanArray/chan_array.csv", header=None, index=None)